enum Inputs :unsigned char {
	ESC, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,

	TINDLE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, BACKSPACE,
	TAB, Q, W, E, R, T, Y, U, I, O, P, L_BRACKET, R_BRACKET, BACKSLASH,
	CAPS_LOCK, A, S, D, F, G, H, J, K, L, COLON, QUOTE, ENTER,
	L_SHIFT, Z, X, C, V, B, N, M, COMMA, PERIOD, FORSLASH, R_SHIFT,
	L_CTRL, L_ALT, SPACE, R_ALT, R_CTRL,

	SHIFT, CTRL, ALT,

	SNAPSHOT, SCROLL_LOCK, PAUSE,
	INSERT, HOME, PGUP, DEL, END, PGDOWN,

	PRINT, SELECT, EXECUTE, CLEAR, HELP, APPS, SLEEP,

	LEFT, UP, DOWN, RIGHT,

	NUM_LOCK, NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
	NUM_MULT, NUM_ADD, NUM_SEPARATOR, NUM_SUBTRACT, NUM_DECIMAL, NUM_DIVIDE,

	LEFT_MOUSE, RIGHT_MOUSE, MIDDLE_MOUSE, SIDE_FRONT_MOUSE, SIDE_BACK_MOUSE,

	BUTTON_COUNT
};

struct Button_State {
	bool down;
	bool changed;
};



struct Input {
	

	POINT mouse;
};